export const INGREDIENTS = [
  { id: 'daepa', name: '대파', emoji: '🌱', unit: '1단', price: 1500, shelfLifeDays: 7, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/CSA-Red-Spring-Onions.jpg/330px-CSA-Red-Spring-Onions.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'pork', name: '돼지고기', emoji: '🥩', unit: '1근', price: 9000, shelfLifeDays: 3, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Schweinebauch-2.jpg/330px-Schweinebauch-2.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'egg', name: '계란', emoji: '🥚', unit: '10구', price: 3500, shelfLifeDays: 20, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Eggs_in_carton.jpg/500px-Eggs_in_carton.jpg' },
  { id: 'tofu', name: '두부', emoji: '⬜', unit: '1모', price: 1800, shelfLifeDays: 5, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Japanese_SilkyTofu_%28Kinugoshi_Tofu%29.JPG/330px-Japanese_SilkyTofu_%28Kinugoshi_Tofu%29.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'onion', name: '양파', emoji: '🧅', unit: '1개', price: 800, shelfLifeDays: 14, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Mixed_onions.jpg/330px-Mixed_onions.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'zucchini', name: '애호박', emoji: '🥒', unit: '1개', price: 1500, shelfLifeDays: 6, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/CSA-Striped-Zucchini.jpg/330px-CSA-Striped-Zucchini.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'kimchi', name: '김치', emoji: '🥬', unit: '1포기', price: 6000, shelfLifeDays: 30, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Various_kimchi.jpg/330px-Various_kimchi.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'milk', name: '우유', emoji: '🥛', unit: '1L', price: 2900, shelfLifeDays: 10, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Glass_of_Milk_%2833657535532%29.jpg/330px-Glass_of_Milk_%2833657535532%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'garlic', name: '마늘', emoji: '🧄', unit: '1kg', price: 5000, shelfLifeDays: 25, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Opened_garlic_bulb_with_garlic_clove.jpg/500px-Opened_garlic_bulb_with_garlic_clove.jpg' },
  { id: 'potato', name: '감자', emoji: '🥔', unit: '1kg', price: 3000, shelfLifeDays: 21, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Patates.jpg/330px-Patates.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },

  // 채소
  { id: 'carrot', name: '당근', emoji: '🥕', unit: '1개', price: 700, shelfLifeDays: 14, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Vegetable-Carrot-Bundle-wStalks.jpg/330px-Vegetable-Carrot-Bundle-wStalks.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'cabbage', name: '배추', emoji: '🥬', unit: '1포기', price: 4000, shelfLifeDays: 10, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Napa_cabbages.png/330px-Napa_cabbages.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'radish', name: '무', emoji: '🤍', unit: '1개', price: 2000, shelfLifeDays: 14, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Different_kinds_of_White_Radish.png/330px-Different_kinds_of_White_Radish.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'beansprout', name: '콩나물', emoji: '🌱', unit: '1봉', price: 1200, shelfLifeDays: 4, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Organic_mixed_beans_shoots.jpg/330px-Organic_mixed_beans_shoots.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'spinach', name: '시금치', emoji: '🥬', unit: '1단', price: 2500, shelfLifeDays: 5, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Spinacia_oleracea_Spinazie_bloeiend.jpg/330px-Spinacia_oleracea_Spinazie_bloeiend.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'chili', name: '고추', emoji: '🌶️', unit: '100g', price: 2000, shelfLifeDays: 7, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Madame_Jeanette_and_other_chillies.jpg/330px-Madame_Jeanette_and_other_chillies.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'cucumber', name: '오이', emoji: '🥒', unit: '1개', price: 800, shelfLifeDays: 7, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/ARS_cucumber.jpg/330px-ARS_cucumber.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'lettuce', name: '상추', emoji: '🥬', unit: '1봉', price: 2500, shelfLifeDays: 5, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Iceberg_lettuce_in_SB.jpg/330px-Iceberg_lettuce_in_SB.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'broccoli', name: '브로콜리', emoji: '🥦', unit: '1개', price: 2500, shelfLifeDays: 10, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Broccoli_and_cross_section_edit.jpg/330px-Broccoli_and_cross_section_edit.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'paprika', name: '파프리카', emoji: '🫑', unit: '1개', price: 1500, shelfLifeDays: 10, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Green-Yellow-Red-Pepper-2009.jpg/330px-Green-Yellow-Red-Pepper-2009.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'eggplant', name: '가지', emoji: '🍆', unit: '1개', price: 1500, shelfLifeDays: 7, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/330px-Solanum_melongena_24_08_2012_%281%29.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },

  // 육류/가공육
  { id: 'beef', name: '소고기', emoji: '🥩', unit: '300g', price: 15000, shelfLifeDays: 4, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Standing-rib-roast.jpg/330px-Standing-rib-roast.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'chicken', name: '닭고기', emoji: '🍗', unit: '1kg', price: 8000, shelfLifeDays: 3, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Chickens_in_market.jpg/330px-Chickens_in_market.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'porkbelly', name: '삼겹살', emoji: '🥓', unit: '500g', price: 12000, shelfLifeDays: 3, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Schweinebauch-2.jpg/330px-Schweinebauch-2.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'groundmeat', name: '다진고기', emoji: '🍖', unit: '300g', price: 7000, shelfLifeDays: 3, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Hackfleisch-1.jpg/500px-Hackfleisch-1.jpg' },
  { id: 'bacon', name: '베이컨', emoji: '🥓', unit: '200g', price: 5500, shelfLifeDays: 10, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/RawBacon.JPG/500px-RawBacon.JPG' },
  { id: 'sausage', name: '소시지', emoji: '🌭', unit: '300g', price: 4500, shelfLifeDays: 14, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Wurstplatte.jpg/330px-Wurstplatte.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },

  // 수산물
  { id: 'mackerel', name: '고등어', emoji: '🐟', unit: '1손', price: 4500, shelfLifeDays: 3, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Trachurus_declivis.jpg/330px-Trachurus_declivis.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'shrimp', name: '새우', emoji: '🍤', unit: '500g', price: 9000, shelfLifeDays: 3, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Cooked_shrimp_on_a_plate.jpg/500px-Cooked_shrimp_on_a_plate.jpg' },
  { id: 'squid', name: '오징어', emoji: '🦑', unit: '1마리', price: 3500, shelfLifeDays: 3, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Arrow_Squid_--_Auckland_Fish_Market_and_Seafood_School_in_New_Zealand_%2850871675792%29.jpg/500px-Arrow_Squid_--_Auckland_Fish_Market_and_Seafood_School_in_New_Zealand_%2850871675792%29.jpg' },
  { id: 'anchovy', name: '멸치', emoji: '🐟', unit: '200g', price: 6000, shelfLifeDays: 60, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Anchovy_closeup.jpg/330px-Anchovy_closeup.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'tunacan', name: '참치캔', emoji: '🥫', unit: '1캔', price: 2500, shelfLifeDays: 365, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Lata_de_at%C3%BAn-Albo.jpg/500px-Lata_de_at%C3%BAn-Albo.jpg' },

  // 유제품/두류
  { id: 'cheese', name: '치즈', emoji: '🧀', unit: '1팩', price: 4500, shelfLifeDays: 21, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Cheese_platter.jpg/330px-Cheese_platter.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'butter', name: '버터', emoji: '🧈', unit: '200g', price: 4000, shelfLifeDays: 60, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Stick-of-butter-salted.jpg/330px-Stick-of-butter-salted.jpg' },
  { id: 'yogurt', name: '요거트', emoji: '🥛', unit: '4개입', price: 3900, shelfLifeDays: 14, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Joghurt.jpg/330px-Joghurt.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'cheonggukjang', name: '청국장', emoji: '🫘', unit: '1팩', price: 3500, shelfLifeDays: 10, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/2015%EB%85%84_2%EC%9B%94_11%EC%9D%BC_%ED%9A%A8%EC%86%8C%EC%9B%90_%EC%B2%AD%EA%B5%AD%EC%9E%A5.jpg/330px-2015%EB%85%84_2%EC%9B%94_11%EC%9D%BC_%ED%9A%A8%EC%86%8C%EC%9B%90_%EC%B2%AD%EA%B5%AD%EC%9E%A5.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },

  // 곡류/면
  { id: 'rice', name: '쌀', emoji: '🌾', unit: '4kg', price: 15000, shelfLifeDays: 180, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Half_a_cup_of_rice._Brown_rice_is_the_best_choice.JPG/330px-Half_a_cup_of_rice._Brown_rice_is_the_best_choice.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'ramen', name: '라면사리', emoji: '🍜', unit: '1개', price: 1000, shelfLifeDays: 90, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Mama_instant_noodle_block.jpg/330px-Mama_instant_noodle_block.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'noodle', name: '국수', emoji: '🍜', unit: '1kg', price: 3000, shelfLifeDays: 180, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Dalian_Liaoning_China_Noodlemaker-01.jpg/330px-Dalian_Liaoning_China_Noodlemaker-01.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'bread', name: '식빵', emoji: '🍞', unit: '1봉', price: 3500, shelfLifeDays: 5, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Korb_mit_Br%C3%B6tchen.JPG/330px-Korb_mit_Br%C3%B6tchen.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'oatmeal', name: '오트밀', emoji: '🥣', unit: '500g', price: 6000, shelfLifeDays: 365, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Oatmeal.jpg/330px-Oatmeal.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },

  // 양념/기타
  { id: 'gochujang', name: '고추장', emoji: '🌶️', unit: '1kg', price: 6000, shelfLifeDays: 365, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Korean_chili_pepper_paste_GOCHUJANG.jpg/330px-Korean_chili_pepper_paste_GOCHUJANG.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'doenjang', name: '된장', emoji: '🫙', unit: '1kg', price: 5500, shelfLifeDays: 365, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Doenjang.jpg/330px-Doenjang.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'soysauce', name: '간장', emoji: '🫙', unit: '900ml', price: 4500, shelfLifeDays: 365, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Soy_sauce_2.jpg/330px-Soy_sauce_2.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'sesameoil', name: '참기름', emoji: '🫙', unit: '320ml', price: 8000, shelfLifeDays: 365, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/SesameSeedOil.png/330px-SesameSeedOil.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'ginger', name: '생강', emoji: '🧄', unit: '200g', price: 2000, shelfLifeDays: 21, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Cultivo_de_Jengibre_%28Zingiber_officinale%29%2C_Takiwasi%2C_Per%C3%BA.jpg/500px-Cultivo_de_Jengibre_%28Zingiber_officinale%29%2C_Takiwasi%2C_Per%C3%BA.jpg' },
  { id: 'cheongyangchili', name: '청양고추', emoji: '🌶️', unit: '100g', price: 1500, shelfLifeDays: 7, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Madame_Jeanette_and_other_chillies.jpg/330px-Madame_Jeanette_and_other_chillies.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'perillaleaf', name: '깻잎', emoji: '🌿', unit: '1봉', price: 2000, shelfLifeDays: 7, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Perilla_frutescens%27_foliage.jpg/500px-Perilla_frutescens%27_foliage.jpg' },
  { id: 'shiitake', name: '표고버섯', emoji: '🍄', unit: '1팩', price: 3500, shelfLifeDays: 10, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Shiitakegrowing.jpg/330px-Shiitakegrowing.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'enokimushroom', name: '팽이버섯', emoji: '🍄', unit: '1봉', price: 1500, shelfLifeDays: 7, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flammulina_velutipes_%28Enokitake%2C_winter_mushroom%29.jpg/330px-Flammulina_velutipes_%28Enokitake%2C_winter_mushroom%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
  { id: 'tomato', name: '토마토', emoji: '🍅', unit: '1개', price: 1000, shelfLifeDays: 7, imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Tomato_je.jpg/330px-Tomato_je.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail' },
];

export const RECIPES = [
  {
    id: 'kimchi-jjigae',
    name: '김치찌개',
    emoji: '🍲',
    mainIngredients: ['kimchi', 'pork', 'onion', 'garlic'],
    steps: '1. 냄비에 돼지고기를 볶는다.\n2. 김치를 넣고 함께 볶는다.\n3. 물을 붓고 양파, 마늘을 넣어 끓인다.\n4. 간을 맞추고 한소끔 더 끓인다.',
  },
  {
    id: 'egg-jjim',
    name: '계란찜',
    emoji: '🍳',
    mainIngredients: ['egg', 'daepa'],
    steps: '1. 계란을 풀고 물과 소금을 섞는다.\n2. 다진 대파를 넣는다.\n3. 뚝배기에 담아 약불로 익힌다.',
  },
  {
    id: 'doenjang-jjigae',
    name: '된장찌개',
    emoji: '🍜',
    mainIngredients: ['tofu', 'zucchini', 'onion', 'potato'],
    steps: '1. 육수에 된장을 푼다.\n2. 감자, 양파를 넣고 끓인다.\n3. 두부와 애호박을 넣고 마저 끓인다.',
  },
  {
    id: 'daepa-bokkeumbap',
    name: '대파달걀볶음밥',
    emoji: '🍚',
    mainIngredients: ['daepa', 'egg', 'garlic'],
    steps: '1. 팬에 마늘과 대파를 볶아 향을 낸다.\n2. 밥을 넣고 함께 볶는다.\n3. 계란을 스크램블해 섞는다.',
  },
  {
    id: 'tofu-jorim',
    name: '두부조림',
    emoji: '🍱',
    mainIngredients: ['tofu', 'daepa', 'garlic'],
    steps: '1. 두부를 도톰하게 썰어 굽는다.\n2. 양념장을 만들어 끼얹는다.\n3. 약불에서 조려낸다.',
  },
  {
    id: 'gamja-tang',
    name: '감자탕',
    emoji: '🍛',
    mainIngredients: ['potato', 'pork', 'onion', 'garlic'],
    steps: '1. 돼지등뼈를 삶아 잡내를 없앤다.\n2. 감자, 양파, 마늘을 넣고 끓인다.\n3. 깻잎과 대파를 올려 마무리한다.',
  },
  {
    id: 'milk-tofu-soup',
    name: '두부계란국',
    emoji: '🥣',
    mainIngredients: ['tofu', 'egg', 'daepa'],
    steps: '1. 육수를 끓인다.\n2. 두부를 넣고 끓인다.\n3. 계란을 풀어 넣고 대파로 마무리한다.',
  },

  // 국/찌개류
  {
    id: 'beef-muguk',
    name: '소고기무국',
    emoji: '🍲',
    mainIngredients: ['beef', 'radish', 'garlic', 'daepa'],
    steps: '1. 소고기를 참기름에 볶는다.\n2. 무를 넣고 함께 볶는다.\n3. 물을 붓고 끓이다 마늘, 대파로 마무리한다.',
  },
  {
    id: 'beansprout-soup',
    name: '콩나물국',
    emoji: '🍲',
    mainIngredients: ['beansprout', 'garlic', 'daepa'],
    steps: '1. 냄비에 콩나물과 물을 넣고 뚜껑을 덮어 끓인다.\n2. 마늘을 넣고 간을 맞춘다.\n3. 대파를 넣고 마무리한다.',
  },
  {
    id: 'sundubu-jjigae',
    name: '순두부찌개',
    emoji: '🍲',
    mainIngredients: ['tofu', 'egg', 'onion', 'gochujang'],
    steps: '1. 양파를 볶다가 고추장을 넣어 볶는다.\n2. 물을 붓고 끓인다.\n3. 두부를 넣고 계란을 풀어 넣는다.',
  },
  {
    id: 'cheonggukjang-jjigae',
    name: '청국장찌개',
    emoji: '🍲',
    mainIngredients: ['cheonggukjang', 'tofu', 'onion', 'potato'],
    steps: '1. 쌀뜨물에 감자, 양파를 넣고 끓인다.\n2. 청국장을 풀어 넣는다.\n3. 두부를 넣고 한소끔 더 끓인다.',
  },
  {
    id: 'budae-jjigae',
    name: '부대찌개',
    emoji: '🍲',
    mainIngredients: ['sausage', 'kimchi', 'tofu', 'ramen'],
    steps: '1. 냄비에 김치와 소시지를 담는다.\n2. 두부와 육수를 붓고 끓인다.\n3. 라면사리를 넣고 익힌다.',
  },

  // 볶음/구이류
  {
    id: 'jeyuk-bokkeum',
    name: '제육볶음',
    emoji: '🍖',
    mainIngredients: ['porkbelly', 'gochujang', 'onion', 'garlic'],
    steps: '1. 고추장 양념을 만든다.\n2. 돼지고기를 양념에 재운다.\n3. 양파, 마늘과 함께 센 불에 볶는다.',
  },
  {
    id: 'ojingeo-bokkeum',
    name: '오징어볶음',
    emoji: '🦑',
    mainIngredients: ['squid', 'onion', 'gochujang', 'cheongyangchili'],
    steps: '1. 오징어를 손질해 썬다.\n2. 고추장 양념을 만든다.\n3. 양파, 청양고추와 함께 센 불에 볶는다.',
  },
  {
    id: 'shrimp-fried-rice',
    name: '새우볶음밥',
    emoji: '🍤',
    mainIngredients: ['shrimp', 'egg', 'onion', 'garlic'],
    steps: '1. 마늘과 양파를 볶아 향을 낸다.\n2. 새우를 넣고 볶는다.\n3. 밥과 계란을 넣어 볶는다.',
  },
  {
    id: 'beef-bokkeum',
    name: '소고기볶음',
    emoji: '🥩',
    mainIngredients: ['beef', 'onion', 'garlic', 'sesameoil'],
    steps: '1. 소고기를 참기름과 마늘로 밑간한다.\n2. 팬에 양파와 함께 볶는다.\n3. 마늘로 향을 더한다.',
  },
  {
    id: 'dakgalbi',
    name: '닭갈비',
    emoji: '🍗',
    mainIngredients: ['chicken', 'gochujang', 'cabbage', 'onion'],
    steps: '1. 닭고기를 고추장 양념에 재운다.\n2. 양배추, 양파를 큼직하게 썬다.\n3. 센 불에 다 함께 볶는다.',
  },
  {
    id: 'mackerel-gui',
    name: '고등어구이',
    emoji: '🐟',
    mainIngredients: ['mackerel', 'soysauce', 'ginger'],
    steps: '1. 고등어에 생강즙과 간장으로 밑간한다.\n2. 팬이나 오븐에 노릇하게 굽는다.',
  },
  {
    id: 'bacon-potato-bokkeum',
    name: '베이컨감자볶음',
    emoji: '🥓',
    mainIngredients: ['bacon', 'potato', 'onion'],
    steps: '1. 감자를 채 썰어 물에 헹군다.\n2. 베이컨을 먼저 볶는다.\n3. 감자, 양파를 넣어 함께 볶는다.',
  },

  // 무침/반찬류
  {
    id: 'spinach-namul',
    name: '시금치나물',
    emoji: '🥬',
    mainIngredients: ['spinach', 'garlic', 'sesameoil'],
    steps: '1. 시금치를 데쳐 찬물에 헹군다.\n2. 물기를 짠다.\n3. 마늘, 참기름으로 무친다.',
  },
  {
    id: 'beansprout-muchim',
    name: '콩나물무침',
    emoji: '🌱',
    mainIngredients: ['beansprout', 'garlic', 'sesameoil'],
    steps: '1. 콩나물을 삶아 헹군다.\n2. 물기를 뺀다.\n3. 마늘, 참기름으로 무친다.',
  },
  {
    id: 'cucumber-muchim',
    name: '오이무침',
    emoji: '🥒',
    mainIngredients: ['cucumber', 'garlic', 'cheongyangchili'],
    steps: '1. 오이를 얇게 썬다.\n2. 마늘, 청양고추를 다진다.\n3. 양념과 함께 버무린다.',
  },
  {
    id: 'lettuce-salad',
    name: '상추겉절이',
    emoji: '🥬',
    mainIngredients: ['lettuce', 'onion', 'soysauce'],
    steps: '1. 상추를 먹기 좋게 뜯는다.\n2. 양파를 얇게 썬다.\n3. 간장 양념으로 무친다.',
  },

  // 면/밥류
  {
    id: 'kimchi-fried-rice',
    name: '김치볶음밥',
    emoji: '🍚',
    mainIngredients: ['kimchi', 'egg', 'onion'],
    steps: '1. 김치와 양파를 볶는다.\n2. 밥을 넣고 함께 볶는다.\n3. 계란후라이를 올린다.',
  },
  {
    id: 'ramen-recipe',
    name: '라면',
    emoji: '🍜',
    mainIngredients: ['ramen', 'egg', 'daepa'],
    steps: '1. 물을 끓이고 라면사리와 스프를 넣는다.\n2. 계란을 풀어 넣는다.\n3. 대파를 올려 마무리한다.',
  },
  {
    id: 'janchi-guksu',
    name: '잔치국수',
    emoji: '🍜',
    mainIngredients: ['noodle', 'egg', 'daepa', 'garlic'],
    steps: '1. 멸치육수를 마늘과 함께 끓인다.\n2. 국수를 삶아 헹군다.\n3. 육수를 붓고 지단, 대파를 올린다.',
  },
  {
    id: 'tuna-mayo-bowl',
    name: '참치마요덮밥',
    emoji: '🍚',
    mainIngredients: ['tunacan', 'egg', 'onion'],
    steps: '1. 참치캔의 기름을 뺀다.\n2. 양파를 잘게 다져 참치와 섞는다.\n3. 밥 위에 올리고 계란후라이를 얹는다.',
  },
  {
    id: 'egg-fried-rice',
    name: '계란볶음밥',
    emoji: '🍳',
    mainIngredients: ['egg', 'daepa', 'garlic'],
    steps: '1. 마늘, 대파를 볶아 향을 낸다.\n2. 계란을 스크램블한다.\n3. 밥을 넣고 함께 볶는다.',
  },

  // 기타
  {
    id: 'potato-julienne',
    name: '감자채볶음',
    emoji: '🥔',
    mainIngredients: ['potato', 'carrot', 'onion'],
    steps: '1. 감자와 당근을 채 썬다.\n2. 감자를 물에 헹군다.\n3. 팬에 양파와 함께 볶는다.',
  },
  {
    id: 'zucchini-jeon',
    name: '애호박전',
    emoji: '🥒',
    mainIngredients: ['zucchini', 'egg'],
    steps: '1. 애호박을 동그랗게 썬다.\n2. 밀가루, 계란물을 입힌다.\n3. 팬에 노릇하게 부친다.',
  },
  {
    id: 'tofu-kimchi',
    name: '두부김치',
    emoji: '🥬',
    mainIngredients: ['tofu', 'kimchi', 'porkbelly'],
    steps: '1. 두부를 삶아 썬다.\n2. 삼겹살을 볶다가 김치를 넣어 볶는다.\n3. 두부와 함께 곁들인다.',
  },
  {
    id: 'broccoli-bokkeum',
    name: '브로콜리볶음',
    emoji: '🥦',
    mainIngredients: ['broccoli', 'garlic', 'sesameoil'],
    steps: '1. 브로콜리를 데친다.\n2. 마늘을 볶아 향을 낸다.\n3. 브로콜리를 넣고 참기름으로 볶는다.',
  },
  {
    id: 'dakbokkeumtang',
    name: '닭볶음탕',
    emoji: '🍗',
    mainIngredients: ['chicken', 'potato', 'carrot', 'gochujang'],
    steps: '1. 닭고기를 데쳐낸다.\n2. 고추장 양념을 만든다.\n3. 감자, 당근과 함께 조린다.',
  },
  {
    id: 'cheese-egg-toast',
    name: '치즈계란토스트',
    emoji: '🍞',
    mainIngredients: ['bread', 'egg', 'cheese'],
    steps: '1. 계란물을 만들어 식빵을 적신다.\n2. 팬에 노릇하게 굽는다.\n3. 치즈를 올려 녹인다.',
  },
  {
    id: 'mushroom-bokkeum',
    name: '버섯볶음',
    emoji: '🍄',
    mainIngredients: ['shiitake', 'enokimushroom', 'garlic', 'sesameoil'],
    steps: '1. 버섯을 먹기 좋게 찢는다.\n2. 마늘을 볶아 향을 낸다.\n3. 버섯을 넣고 참기름으로 볶는다.',
  },
  {
    id: 'paprika-bokkeum',
    name: '파프리카볶음',
    emoji: '🫑',
    mainIngredients: ['paprika', 'onion', 'garlic'],
    steps: '1. 파프리카와 양파를 채 썬다.\n2. 마늘을 볶아 향을 낸다.\n3. 채소를 넣고 센 불에 볶는다.',
  },
  {
    id: 'eggplant-bokkeum',
    name: '가지볶음',
    emoji: '🍆',
    mainIngredients: ['eggplant', 'garlic', 'soysauce'],
    steps: '1. 가지를 길게 썬다.\n2. 마늘을 볶아 향을 낸다.\n3. 가지와 간장 양념을 넣고 볶는다.',
  },
  {
    id: 'oatmeal-porridge',
    name: '오트밀죽',
    emoji: '🥣',
    mainIngredients: ['oatmeal', 'milk', 'egg'],
    steps: '1. 냄비에 우유를 데운다.\n2. 오트밀을 넣고 저으며 끓인다.\n3. 계란을 풀어 넣고 한소끔 더 끓인다.',
  },
];
